
// This file is generated by Fragment. Do not edit it.

import * as transition0 from "./fade.js";
import * as transition1 from "./splitX.js";
import * as transition2 from "./splitY.js";

export const transitions = {
    "fade.js": transition0,
    "splitX.js": transition1,
    "splitY.js": transition2,
};
