import path from 'node:path';
import { readFile, writeFile } from 'node:fs/promises';
import { log } from './log.js';
import { __dirname, file, mkdirp } from './utils.js';

export const FRAGMENT_DIRECTORY = '/.fragment';

/**
 * Create local tsconfig.json file
 * @param {string} cwd Current working directory
 * @returns {string}
 */
export async function createTsConfigFile(cwd = process.cwd()) {
	try {
		const dirpath = path.join(cwd, FRAGMENT_DIRECTORY);
		const filepath = path.join(dirpath, 'tsconfig.json');

		const fragmentPath = path.relative(dirpath, __dirname);

		// Generate tsconfig.json file
		const tsConfigCode = `
// This file is generated by Fragment. Do not edit it.
{
	"compilerOptions": {
		"target": "ESNext",
		"useDefineForClassFields": true,
		"module": "ESNext",
		"lib": ["ESNext", "DOM", "DOM.Iterable"],
		"skipLibCheck": true,

		/* Bundler mode */
		"moduleResolution": "bundler",
		"allowImportingTsExtensions": true,
		"isolatedModules": true,
		"esModuleInterop": false,
		"moduleDetection": "force",
		"resolveJsonModule": true,
		"noEmit": true,

		/* Linting */
		"strict": true,
		"allowJs": true,
		"checkJs": false,
		"noUnusedLocals": true,
		"noUnusedParameters": true,
		"noFallthroughCasesInSwitch": true,
		"noUncheckedSideEffectImports": true,
		"allowSyntheticDefaultImports": true,
		"forceConsistentCasingInFileNames": true,

		/* Paths */
		"paths": {
			"@fragment/config": ["${path.join(fragmentPath, 'src/cli/config.js')}"],
			"@fragment/types": ["${path.join(fragmentPath, 'src/types')}"],
			"@fragment/types/*": ["${path.join(fragmentPath, 'src/types')}/*"],
			"@fragment/*": ["${path.join(fragmentPath, 'src/client/app')}/*"]
		}
	}
}
`;

		await mkdirp(dirpath);
		await writeFile(filepath, tsConfigCode);

		return filepath;
	} catch (error) {
		throw error;
	}
}
