import path from 'node:path';
import { readFile, writeFile } from 'node:fs/promises';
import { log } from './log.js';
import { __dirname, file, mkdirp } from './utils.js';

export const FRAGMENT_DIRECTORY = '/node_modules/.fragment';

/**
 * Create local sketches file needed by Fragment
 * @param {string[]} entries
 * @param {string} [cwd=process.cwd()] Current working directory
 * @returns {string}
 */
export async function createSketchesFile(entries = [], cwd = process.cwd()) {
	try {
		function getFilenameFromEntries(entries) {
			if (entries.length === 1) {
				const filename = path.parse(entries[0]).name;

				return `${filename}.js`;
			}

			return `sketches.js`;
		}

		log.info(`Generating files...`);

		const dirpath = path.join(cwd, FRAGMENT_DIRECTORY);
		const filename = getFilenameFromEntries(entries);
		const filepath = path.join(dirpath, filename);

		// Generate sketches.js file
		const sketchesJsCode = `
// This file is generated by Fragment. Do not edit it.
export const sketches = {
	${entries
		.map((entry) => {
			const entryPath = entry.split(path.sep).join(path.posix.sep);
			const relativeEntryPath = `../../${entry}`
				.split(path.sep)
				.join(path.posix.sep);
			return `"${entryPath}": () => import("${relativeEntryPath}")`;
		})
		.join(',\n\t')}
};

export const onSketchReload = (fn) => {
	if (import.meta.hot) {
		import.meta.hot.data.onSketchChange = fn;
	}
};

if (import.meta.hot) {
	import.meta.hot.accept((m) => {
		if (typeof import.meta.hot.data.onSketchChange === 'function') {
			import.meta.hot.data.onSketchChange(m);
		}
	});
}
`;

		await mkdirp(dirpath);
		await writeFile(filepath, sketchesJsCode);

		return filepath;
	} catch (error) {
		throw error;
	}
}

/**
 * Create local tsconfig.json file
 * @param {string} cwd Current working directory
 * @returns {string}
 */
export async function createTsConfigFile(cwd = process.cwd()) {
	try {
		const dirpath = path.join(cwd, FRAGMENT_DIRECTORY);
		const filename = 'tsconfig.json';
		const filepath = path.join(dirpath, filename);

		const fragmentPath = path.relative(dirpath, __dirname);

		// Generate tsconfig.json file
		const tsConfigCode = `
// This file is generated by Fragment. Do not edit it.
{
	"compilerOptions": {
		"target": "ESNext",
		"useDefineForClassFields": true,
		"module": "ESNext",
		"lib": ["ESNext", "DOM", "DOM.Iterable"],
		"skipLibCheck": true,

		/* Bundler mode */
		"moduleResolution": "bundler",
		"allowImportingTsExtensions": true,
		"isolatedModules": true,
		"esModuleInterop": false,
		"moduleDetection": "force",
		"resolveJsonModule": true,
		"noEmit": true,

		/* Linting */
		"strict": true,
		"allowJs": true,
		"checkJs": false,
		"noUnusedLocals": true,
		"noUnusedParameters": true,
		"noFallthroughCasesInSwitch": true,
		"noUncheckedSideEffectImports": true,
		"allowSyntheticDefaultImports": true,
		"forceConsistentCasingInFileNames": true,

		/* Paths */
		"paths": {
			"@fragment/types": ["${path.join(fragmentPath, 'src/types')}"],
			"@fragment/types/*": ["${path.join(fragmentPath, 'src/types')}/*"],
			"@fragment/*": ["${path.join(fragmentPath, 'src/client/app')}/*"]
		}
	}
}
`;

		await mkdirp(dirpath);
		await writeFile(filepath, tsConfigCode);

		return filepath;
	} catch (error) {
		throw error;
	}
}
