import fs from "fs/promises";
import path from "path";
import log from "./log.js";
import { start as startServer } from "./server.js";

import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const timestamp = Date.now();

export const run = async (entry, options) => {
    try {
        const entries = await createEntries(entry, options);

        if (entries.length > 0) {
            const filepaths = await generateFiles(entries, options);
            await startServer({
                options,
                timestamp,
                filepaths,
                entries,
            });
        }
    } catch(error) {
        console.log(error);
    }
};

async function createEntries(entry, options) {
    if (entry === undefined) {
        log.error(`Missing argument.`)
        console.log(" Use --new flag to let fragment create the file.");
        return;
    }
    
    const entries = [];
    const shouldCreateFile = options.new;

    async function createEntryFile(entryPath) {
        const templates = {
            "2d": "./templates/2d.js",
            "three/orthographic": "./templates/three-orthographic.js",
            "three/perspective": "./templates/three-perspective.js",
            "ogl/orthographic": "./templates/ogl-orthographic.js",
            "ogl/perspective": "./templates/ogl-perspective.js",
            "default": "./templates/default.js",
        };

        const createFromTemplate = typeof options.template === "string";
        const template = createFromTemplate ? templates[options.template] : templates.default;

        if (!template) {
            log.error(`Wrong argument value.`);
            console.log(`Template ${options.template} doesn't exist.\nPossible values are:`);
            Object.keys(templates).forEach((key) => {
                console.log(key);
            });
            return;
        }

        const templatePath = path.join(__dirname, template);
        const templateContent = await fs.readFile(templatePath);

        await fs.writeFile(entryPath, templateContent);

        console.log(`${log.prefix} Created ${entry} on disk.`);
    }

    const entryPath = path.join(process.cwd(), entry);

    try {
        const stats = await fs.lstat(entryPath);

        if (stats.isDirectory()) {
            const files = await fs.readdir(entryPath);
            const sketchFiles = files.filter((file) => path.extname(file) === ".js");

            if (sketchFiles.length === 0) {
                log.error(`Folder doesn't contain any sketch files.`);
                console.log("Use --new flag to start working on a sketch.");
                return;
            }

            entries.push(...sketchFiles.map((sketchFile) => path.relative(process.cwd(), sketchFile)));
        } else if (stats.isFile()) {
            if (shouldCreateFile) {
                log.warning(`Ignored argument:`);
                console.log(`${entry} already exists.`);
            }

            entries.push(path.relative(process.cwd(), entryPath));
        }
    } catch(error) {
        if (error.code === "ENOENT") {
            if (shouldCreateFile) {
                await createEntryFile(entryPath);
            } else {
                log.error(`Missing file: ${entry} doesn't exist.`)
                console.log("Use --new flag to create the file automatically");
            }
        }
    }

    

    return entries;
}

async function generateFiles(entries, options) {
    const dir = "/node_modules/.fragment";
    const dirpath = path.join(process.cwd(), dir);
    const filename = `sketches.js`;

    // create directory and don't throw error if it already exists
    try {
		await fs.mkdir(dirpath, { recursive: true });
	} catch (e) {
		if (e.code !== 'EEXIST') {
            throw e;
        }
	}


    const code = `
// This file is generated by Fragment. Do not edit it.

${entries.map((entry, index) => {
return `import * as sketch${index} from "../../${entry}";`;
}).join("\n")}

export const sketches = {
    ${entries.map((entry, index) => {
        return `"${entry}": sketch${index}`
    }).join(',')
    }
};`;

    const filepath = path.join(dirpath, filename);

    await fs.writeFile(filepath, code);

    console.log(`${log.prefix} Generated ${dir}/${filename} from entries:`);
    entries.forEach(entry => console.log(entry));

    const filepathProps = path.join(dirpath, 'props.js');


    await fs.writeFile(filepathProps, `
// This file is generated by Fragment. Do not edit it.

export let rendering = "${options.rendering}";
export let sketchesCount = ${entries.length};
export let sketchFiles = [${entries.map((entry, index) => {
        return `"${entry}"`;
    }).join(',')}];
`);
    return [filepath, filepathProps];
}
