// This file is generated by Fragment. Do not edit it.

import Example from "/Example.js";

const scenes = [
    { load: () => import ("/Cubes.js") }
];

Promise.all(scenes.map(scene => scene.load()))
    .then((all) => {
        all.forEach(scene => {
            scene.init();
        })
    });

Example();
