// This file is generated by Fragment. Do not edit it.
import { init as initRenderer } from "/fragment/renderers/THREERenderer.js";

const scenes = [
    { load: () => import ("/Cubes.js") }
];

Promise.all(scenes.map(scene => scene.load()))
    .then((all) => {
        all.forEach((scene, index) => {
            scenes[index].instance = scene;
        });

        let renderer = initRenderer();

        let scene = scenes[0].instance;

        scene.init();
        scene.resize(renderer.domElement.width, renderer.domElement.height);

        let update = () => {
            console.log(scene.fps);
            
            scene.update({ renderer });

            requestAnimationFrame(() => {
                update();
            });
        };

        update();

        if (import.meta.hot) {
            import.meta.hot.accept(({ module }) => {
                console.log("Module ::", module);
            });
        }
    });
